import React, { useState } from "react";
import Image from "next/image";
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";
import Head from "next/head";
import { uploadcareLoader } from "@uploadcare/nextjs-loader";
import dynamic from "next/dynamic";
import JSON_DATA from "./json/iot.json";
import {
  MdAnimation,
  MdLaunch,
  MdOutlineDashboardCustomize,
} from "react-icons/md";
import { FaConnectdevelop, FaCreativeCommonsRemix } from "react-icons/fa";
import { SiCraftcms } from "react-icons/si";
import Link from "next/link";
import Portfolio from "./components/Portfolio";
const FaqSection = dynamic(() => import("../components/FaqSection"), {
  loading: () => <p>Loading...</p>,
});
const Header = dynamic(() => import("../components/Header"), {
  loading: () => <p>Loading...</p>,
});
const BlogSection = dynamic(() => import("../components/BlogSection"), {
  loading: () => <p>Loading...</p>,
});
const TalkExpert = dynamic(() => import("../components/TalkExpert"), {
  ssr: false,
  loading: () => <p>Loading...</p>,
});
const HeroSectionForm = dynamic(() => import("../components/HeroSectionForm"), {
  loading: () => <p>Loading...</p>,
});
const HireSection = dynamic(() => import("../components/HireSection"), {
  loading: () => <p>Loading...</p>,
});
const Advice = dynamic(() => import("../components/Advice"), {
  loading: () => <p>Loading...</p>,
});
const NewSection = dynamic(() => import("../components/NewSection"), {
  loading: () => <p>Loading...</p>,
});
const ContactFromCenter = dynamic(
  () => import("../components/ContactFromCenter"),
  {
    loading: () => <p>Loading...</p>,
  }
);
const ServiceSection = dynamic(() => import("../components/ServiceSection"), {
  loading: () => <p>Loading...</p>,
});

const Platforms = [
  {
    num: "1",
    img: "/img/iot-consulting-service-icon.svg",
    title: "IoT Consulting Service",
    urlLink: "ca/application-consulting-services",
    decs: "Our IoT development service is far beyond technical capabilities. We offer consulting services for those who decide to integrate IoT solutions from scratch for Android app development for IoT. Our experts will help you to turn the idea into reality with high-quality solutions. We will assist you in optimizing your business functions. Our experts will determine the requirements and let the business automate existing business processes with the help of IoT.",
  },
  {
    num: "2",
    img: "/img/embedded-software-development.svg",
    title: "Embedded Software Development",
    decs: "Comfygen develops embedded and firmware systems to integrate smart devices into IoT infrastructure with the Internet of Things app development services. Our Embedded Software Development service with IoT incorporates cutting-edge technology to develop intelligent and interconnected systems. Our experts help design, develop, and optimize embedded software for IoT devices for seamless communication, data processing, and remote control. ",
  },
  {
    num: "3",
    img: "/img/mobile-apps-for-connected-devices.svg",
    title: "Mobile Apps for Connected Devices",
    decs: "As part of our Internet of Things application development, we design native and cross-platform mobile apps. This will provide you with on-the-go access to data generated by smart devices and act as remote controls for IoT solutions such as indoor navigation and geofencing apps, Mobile apps for wearables, Image recognition apps, and Contactless payment solutions.",
  },
  {
    num: "4",
    img: "/img/iot-dashboards.svg",
    title: "IoT Dashboards",
    decs: "With the help of Comfygen, businesses can easily configure IoT devices. It will aid in managing cyber-physical systems both onsite and remotely. You can analyze sensor data and present it on interactive dashboards. IoT Dashboards offer intuitive and real-time visualization of connected device data. With customizable widgets and insightful analytics, users can monitor performance, detect anomalies, and make informed decisions. Our dashboards provide a user-friendly interface for managing and optimizing IoT networks, enhancing efficiency, and driving actionable insights. ",
  },
  {
    num: "5",
    img: "/img/iot-app-development-services.svg",
    title: "IoT App Development Services",
    decs: "Our IoT App Development Services specialize in creating scalable and secure applications for connected devices. From conceptualization to deployment, we design intuitive interfaces and robust functionalities tailored to your IoT ecosystem. Our IoT application development services company offers solutions that enable seamless device management, data visualization, and remote control, driving innovation and enhancing user experiences.",
  },
];
const Industry = [
  {
    src: "/img/finance-icon-img.webp",
    dec: "Finance",
  },
  {
    src: "/img/healthcare-icon.webp",
    dec: "Healthcare",
  },
  {
    src: "/img/education-icon-img.webp",
    dec: "Education",
  },
  {
    src: "/img/communiaction.webp",
    dec: "Communiaction",
  },
  {
    src: "/img/manufacturing-icon.webp",
    dec: "Manufacturing",
  },
  {
    src: "/img/transportation-icon.webp",
    dec: "Transportation",
  },
  {
    src: "/img/real-estate.webp",
    dec: "Real Estate",
  },
  {
    src: "/img/energy-img.webp",
    dec: "Energy",
  },
];
export default function Altcoin(props) {
  let { initialData } = props;

  let { Modus } = JSON_DATA;

  return (
    <>
      <Head>
        <title>
          Leading IoT Development Company In India & The USA | Comfygen
        </title>
        <meta
          name="description"
          content="Comfygen is a leading IoT development company in India and the USA, that offers IoT consultancy services through our expert IoT developers and consultants. Contact us today for a free consultation."
        />
        <link
          rel="canonical"
          href="https://www.comfygen.com/iot-development-company"
        />
        <meta property="og:locale" content="en_US" />
        <meta property="og:type" content="article" />
        <meta
          property="og:title"
          content="Leading IoT Development Company In India & The USA | Comfygen"
        />
        <meta
          property="og:description"
          content=" Comfygen is a leading IoT development company in India, that offers IoT consultancy services through our expert IoT developers and consultants. Contact us today for a free consultation."
        />
        <meta
          property="og:url"
          content="https://www.comfygen.com/iot-development-company"
        />
        <meta property="og:site_name" content="Comfygen" />
        <meta
          property="article:publisher"
          content="https://www.facebook.com/people/Comfygen-Private-Limited/100083835361397/"
        />
        <meta
          property="article:modified_time"
          content="2022-12-26T08:12:32+00:00"
        />
        <meta
          property="og:image"
          content="https://www.comfygen.com/images/next-js-development"
        />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:site" content="@comfygentech" />
        <meta name="twitter:label1" content="Est. reading time" />
        <meta name="twitter:data1" content="14 minutes" />
        <meta charSet="UTF-8" />
        <meta
          property="og:facebook_title"
          content="Top-notch IoT Development Company In India"
        />
        <meta
          property="og:facebook_description"
          content="Comfygen is a leading IoT development company in India and The USA, that offers IoT consultancy services through our expert IoT developers and App consultants. Contact us today for a free consultation."
        />
        <meta
          property="og:twitter_title"
          content="Custom IoT Development Company In India and The USA."
        />
        <meta
          property="og:twitter_description"
          content="Comfygen offer Best Delivering custom IOT Services and solutions to make businesses more smarter and innovative. Find Top Talent Globally & Launch Your Project Today!"
        />
        <meta property="schema:type" content="Website, Article" />
        <meta name="copyright" content="Comfygen Private Limited" />
        <meta name="language" content="En_US" />
        <meta
          name="abstract"
          content="Internet Of Things (IoT) Development Agency in India | Best team of IoT developers | Comfygen"
        />
        <meta
          name="summary"
          content="Comfygen offer top-notch team of IoT developers for your Business Project, we specializing in Creating and Delivering custom IOT Services, and solutions to make businesses more smarter and innovative. Our expert team is dedicated to enhancing and updating your Internet Of Things (IoT) App Development Services to meet the latest standards."
        />
        <meta name="author" content="Mr. Saddam Husen, sales@comfygen.com" />
        <meta name="reply-to" content="sales@comfygen.com" />
        <meta
          name="owner"
          content="A Founder is one of the individuals who helped establish a comprehensive Custom IoT Development Services & Solutions startup, or organization. They typically share the vision, passion, and responsibility for the success of the venture with other Founders. Founders can have varying levels of involvement."
        />
        <meta
          name="A Top Custom IoT Development Company in India and the USA"
          content="Are you looking to hire the best leading IoT Development for your project? We provide skilled Mobile App developers and programmers for hire."
        />
        <meta
          name="category"
          content="In the current digital landscape, our team of IoT developers ensures that businesses worldwide, spanning various industries, receive tailored IoT development solutions aligned with their specific development needs. Find dedicated IOT App Developers for IOT App with Expertise in Android iot app development and iOS iot app development! Are you ready to transform your business with the power of the Internet of Things (IoT)? Comfygen is your trusted partner for all your IoT Development Solutions."
        />
        <meta name="coverage" content="Worldwide" />
        <meta name="distribution" content="Global" />
        <meta name="rating" content="General" />
        <meta
          name="subtitle"
          content="Discover a specialized IoT Development Company offering dedicated IoT App Developers proficient in Android and iOS IoT app development. Are you prepared to revolutionize your business utilizing the transformative potential of the Internet of Things (IoT)? Partner with Comfygen for comprehensive IoT Development Solutions."
        />
        <meta name="MobileOptimized" content="320" />
        <meta name="fb:page_id" content="110909321596135" />
        <meta name="HandheldFriendly" content="true" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="og:country-name" content="US ,CA,DE" />
        <meta name="og:latitude" content="43.781269°" />
        <meta name="og:longitude" content="-79.230759" />
        <meta
          property="og:type"
          content="Hire Best IOT App development Company In India | offshore Iot App developer or Programmers"
        />
      </Head>
      <div className="overflow-hidden">
        <div
          className="bg-center bg-no-repeat bg-cover "
          style={{ backgroundImage: `url("/img/hero-section-bg.webp")` }}
        >
          <div className=" bg-[#1B1C30CC]">
            <Header />
            <div className="md:py-28 py-5">
              <HeroSectionForm
                heading="Best IoT Development Company"
                ptag="Want to build scalable IoT platforms for your business? Comfygen, the leading IoT app development company, has brought top-notch quality IoT services to today’s business. With over 15+ years of expert experience, we have brought you the best IoT app and software development service. "
                ptag1="Our IoT application development agency promises to deliver service with robust IoT solutions that optimize business operations and improve work safety. Our expertise will assist you in getting exceptional results in IoT development, consultancy, or IoT software development services. Our service will be your go-to destination for IoT development, so if you are looking for innovation to build IoT applications, get in touch with our team."
                btnName="Discuss Now"
                btnLink="/contact-us"
              />
            </div>
          </div>
        </div>
        <Advice
          heading="Best Ever IoT Development Company"
          ptag="Comfygen, one of the top IoT development companies, provides comprehensive Internet of Things solutions to help you overcome the challenges of integrating wearables, sensors, networks, clouds, and applications without compromising security. We help you transform your business with powerful data analytics based on our industry-specific knowledge of Internet of Things development services and expertise in firmware development, mobility, IoT cloud application development, and data analysis."
          ptag1="We use a modular Internet of Things architecture for application building with IoT that enables rapid vertical and horizontal scaling. Whether you are in the early stages or well underway in your IoT journey, the IoT consultants of our top IoT app development companies are ready to ensure you maximize the potential of the latest technologies and adapt them seamlessly. "
          imgSrc="/img/best-ever-iot-development-company.svg"
          imgW={585}
          imgH={559}
          altTag="Best Ever IoT Development Company"
        />
        <ContactFromCenter />

        <div className="space-y-4 w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12 py-10">
          <div className="flex flex-col justify-center text-center">
            <h2 className="py-2 text-[#0E1F51] xl:text-4xl text-3xl font-bold xl:leading-[3rem] ">
              Explore Our{" "}
              <span className="font-bold text-blue-500">
                {" "}
                Services Under IoT{" "}
              </span>{" "}
              Development
            </h2>
            <p>
              Comfygen is recognized as the most reputed and trusted IoT
              development company. We offer a broad range of services under our
              IoT development. Let’s check them out in detail
            </p>
          </div>
          <div className="grid gap-10 py-10 text-left lg:grid-cols-3 md:grid-cols-2 xl:gap-10">
            {Platforms.map((card) => (
              <div
                key={props.key}
                className="p-8 space-y-4 bg-gradient-to-br from-blue-500/10 to-purple-500/20 border  rounded-[40px] transition-all duration-300 hover:translate-y-2 group "
              >
                <a href={props.url} title="service cards" className="space-y-4">
                  <div className="w-20 h-20 p-3 bg-[#ffffff] shadow rounded-[17px] flex justify-center items-center">
                    <img className="w-30 h-30" src={card.img} alt="" />
                  </div>
                  <h3 className="text-lg font-extrabold text-[#0E1F51] transition-all duration-200">
                    <a href={card?.urlLink}>{card.title}</a>
                  </h3>
                  <p className="text-black transition duration-200 ease-in-out">
                    {card.decs}
                  </p>
                </a>
              </div>
            ))}
          </div>
        </div>

        <section
          className="w-full bg-center bg-no-repeat bg-cover"
          style={{ backgroundImage: `url("images/illuslator/phasebg.webp")` }}
        >
          <div className="w-full py-16 bg-gradient-to-b from-blue-500/80 to-indigo-500/80">
            <div className="space-y-4 text-center text-white w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12">
              <h2 className="py- text-[#ffffff] xl:text-4xl text-3xl font-bold xl:leading-[3rem] ">
                Custom IoT Applications For Various Industries for Business
                Productivity
              </h2>
              <p className="text-base">
                Let’s check out the most popular types of IoT applications we
                develop to help various industrial sectors:
              </p>
              <div className="grid gap-16 pt-8 lg:grid-cols-2 md:grid-cols-2 xl:gap-20">
                {JSON_DATA.Process.map((elem) => {
                  const { title, num, decs } = elem;
                  return (
                    <div
                      key={num}
                      className="flex space-x-6 items-left drop-shadow-2xl"
                    >
                      <div>
                        <div className="flex items-center justify-center w-16 h-16 p-2 text-xl font-semibold text-white rounded-full bg-white/20">
                          {num}
                        </div>
                      </div>
                      <div className="text-left">
                        <h2 className="text-lg font-semibold">{title}</h2>
                        <p>{decs}</p>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          </div>
        </section>
        <section className="bg-[#F3F4F6] lg:py-14 py-8">
          <div className="w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12">
            <h2 className="text-4xl font-bold text-[#000] text-start border-b-4 pb-3 ">
              INDUSTRY VERTICALS
            </h2>
            <div className="grid lg:grid-cols-4 md:grid-cols-2  grid-cols-1 gap-10 mt-10">
              {Industry.map((item) => (
                <div className="space-y-2 bg-[#ECEDFE] border text-center p-6 rounded-lg">
                  <img
                    className="flex justify-center mx-auto w-20 h-20"
                    src={item.src}
                    alt=""
                  />
                  <h3 className="lg:text-2xl text-base font-normal">
                    {item.dec}
                  </h3>
                </div>
              ))}
            </div>
          </div>
        </section>
        <section className="py-10">
          <div className="justify-between items-center w-11/12 mx-auto space-y-10 2xl:w-9/12 xl:w-5/6 lg:w-11/12 flex flex-col-reverse lg:flex-row md:space-x-10 md:space-y-0  border-l-4 border-b-4 border-dotted p-4">
            <div className="w-full lg:w-1/2 space-y-6 text-left">
              <div className="space-y-4">
                <h2 className="text-2xl lg:text-4xl font-bold text-[#0E1F51] ">
                  Our Highly Skilled Developers To Care of IoT App Development
                </h2>
              </div>
              <p className="text-base text-black break w-full lg:w-[85%]">
                Our team of highly skilled IoT app developers who are experts in
                IoT development will take care of every aspect of IoT app
                development with their world-class expertise and dedication.
                From conceptualization to deployment, we leverage cutting-edge
                technologies and industry best practices to create robust and
                innovative solutions tailored to your specific requirements.
                Whether you need remote monitoring, real-time analytics, or
                smart device control, our experienced team of IoT application
                development services is committed to delivering exceptional IoT
                apps that drive value for your business and delight your users.
              </p>
            </div>
            <div className="flex justify-center w-full lg:w-1/2 lg:justify-start pb-10 lg:pb-0">
              <Image
                className="rounded-md"
                title="Best iot development Service Provider"
                alt="Best iot development Service Provider"
                src="/img/our-highly-skilled-developers-to-care-of-IoT-app-development.webp"
                height={550}
                width={550}
                loader={uploadcareLoader}
                unoptimized={true}
              />
            </div>
          </div>
          <div className="items-center w-11/12 mx-auto space-y-10 2xl:w-9/12 xl:w-5/6 lg:w-11/12 lg:flex lg:space-x-10 md:space-y-0 border-r-4 border-b-4 border-dotted p-4">
            <div className="flex justify-center w-full lg:w-1/2 lg:justify-start">
              <Image
                className="rounded-md"
                title="IoT Development Solutions"
                alt="IoT Development Solutions"
                src="/img/agile-development.webp"
                height={400}
                width={550}
                loader={uploadcareLoader}
                unoptimized={true}
              />
            </div>
            <div className="w-full lg:w-1/2 space-y-6 text-left">
              <div className="space-y-4">
                <h2 className="text-2xl lg:text-4xl font-bold text-[#0E1F51] ">
                  Check Out the Full Potential of IoT with Our Agile Development
                  Approach
                </h2>
              </div>
              <p className="text-base text-black break">
                Our experts put their best efforts into unleashing the full
                potential of IoT by following a strategic and comprehensive
                approach in order to develop the app. Here are the best
                practices our IoT development firm follows to maximize the
                effectiveness of our IoT App Development Service:
              </p>
            </div>
          </div>
        </section>

        <section className="py-10 bg-gray-100 space-y-10">
          <div className="items-center w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12 lg:flex lg:space-x-10 md:space-y-0 lg:divide-x-2 divide-[#0E1F51]">
            <div className="w-full lg:w-1/2 text-left space-y-6">
              <div className="space-y-4">
                <h2 className="xl:text-4xl text-3xl font-bold text-[#0E1F51] ">
                  Focusing on User-Centric Design:
                </h2>
              </div>
              <p className="text-base text-black">
                {`Our IoT developers prioritize user experience (UX) and usability throughout the app development process. We adopt the user-centric design approach. With a deep understanding of the client’s needs and preferences, we plan the design. Moreover, our Internet of Things app development conducts user research and usability testing to gather insights.`}
              </p>
              <ul className="list-disc px-4 text-base">
                {JSON_DATA.myList1.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </div>
            <div className="flex justify-center w-full lg:w-1/2 lg:justify-end pb-10 lg:pb-0">
              <Image
                src="/img/iot-smart-solutions.webp"
                alt=" IoT Development Services"
                className="rounded-md"
                width={500}
                height={500}
                loader={uploadcareLoader}
                unoptimized={true}
              />
            </div>
          </div>
          <div className="items-center w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12 lg:flex lg:space-x-10 md:space-y-0">
            <div className="flex justify-center w-full lg:w-1/2 lg:justify-start pb-10 lg:pb-0">
              <Image
                src="/img/development-methodology.webp"
                alt=" IoT Development Services"
                className="rounded-md"
                width={500}
                height={500}
                loader={uploadcareLoader}
                unoptimized={true}
              />
            </div>
            <div className="w-full lg:w-1/2 text-left space-y-6 border-2 p-6 border-dashed border-[#0E1F51]">
              <div className="space-y-4">
                <h2 className="xl:text-4xl text-3xl font-bold text-[#0E1F51] ">
                  Agile Development Methodology:
                </h2>
              </div>
              <p className="text-base text-black">
                {`Our custom IoT development company developer team embraces agile development methodologies that bring flexibility, efficiency, collaboration, and iterative delivery. We break down the development cycle into different parts and focus on delivering specific features. We prioritize features based on business value and customer feedback in order to meet changing requirements for IoT mobile app development. Here are the Agile development practices we follow;`}
              </p>
              <ul className="list-disc px-4 text-base">
                {JSON_DATA.myList2.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </div>
          </div>
          <div className="items-center w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12 lg:flex lg:space-x-10 md:space-y-0 lg:divide-x-2 divide-[#0E1F51]">
            <div className="w-full lg:w-1/2 text-left space-y-6">
              <div className="space-y-4">
                <h2 className="xl:text-4xl text-3xl font-bold text-[#0E1F51] ">
                  Following Security and Privacy Standards
                </h2>
              </div>
              <p className="text-base text-black">
                {`Our IoT product development services prioritize integrating robust security and privacy standards into the architecture and design of IoT apps. We focus on the best IoT app by protecting sensitive data and mitigating potential risks. Our experts in the Internet of Things app development company implement strong encryption, authentication, and access control mechanisms for safeguarding data storage and transmission.`}
              </p>
              <ul className="list-disc px-4 text-base">
                {JSON_DATA.myList3.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </div>
            <div className="flex justify-center w-full lg:w-1/2 lg:justify-end pb-10 lg:pb-0">
              <Image
                src="/img/following-security-and-privacy-standards"
                alt=" IoT Development Services"
                className="rounded-md"
                width={500}
                height={500}
                loader={uploadcareLoader}
                unoptimized={true}
              />
            </div>
          </div>
          <div className="items-center w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12 lg:flex lg:space-x-10 md:space-y-0">
            <div className="flex justify-center w-full lg:w-1/2 lg:justify-start pb-10 lg:pb-0">
              <Image
                src="/img/you-should-look-for-features-in-iot-apps.webp"
                alt=" IoT Development Services"
                className="rounded-md"
                width={500}
                height={500}
                loader={uploadcareLoader}
                unoptimized={true}
              />
            </div>
            <div className="w-full lg:w-1/2 text-left space-y-6 border-2 p-6 border-dashed border-[#0E1F51]">
              <div className="space-y-4">
                <h2 className="xl:text-4xl text-3xl font-bold text-[#0E1F51] ">
                  You should look for features in IoT apps!
                </h2>
              </div>
              <p className="text-base text-black">
                {`Comfygen has proven to be a trusted partner for developing mobile app development for IoT with great features and functionality. Our IoT app development solutions will help boost enhanced workflow and streamline management. We also tailor-fit the features as per the business requirements. Here are the key features that our IoT application developers focus on in order to meet their needs effectively:`}
              </p>
            </div>
          </div>
          <div className="items-center w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12 lg:flex lg:space-x-10 md:space-y-0 lg:divide-x-2 divide-[#0E1F51]">
            <div className="w-full lg:w-1/2 text-left space-y-6">
              <div className="space-y-4">
                <h2 className="xl:text-4xl text-3xl font-bold text-[#0E1F51] ">
                  Device Management and Real-Time Data Monitoring
                </h2>
              </div>
              <p className="text-base text-black">
                {`A robust device management feature will let users easily onboard, monitor, monitor, and update IoT apps remotely. On the other hand, the integration of real-time data monitoring capabilities will allow users to track sensor data, device status, and performance metrics in real time. We integrate these features in IoT solution development to aid in;`}
              </p>
              <ul className="list-disc px-4 text-base">
                {JSON_DATA.myList3.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </div>
            <div className="flex justify-center w-full lg:w-1/2 lg:justify-end pb-10 lg:pb-0">
              <Image
                src="/img/device-management-and-real-time-data-monitoring.webp"
                alt=" IoT Development Services"
                className="rounded-md"
                width={500}
                height={500}
                loader={uploadcareLoader}
                unoptimized={true}
              />
            </div>
          </div>
          <div className="items-center w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12 lg:flex lg:space-x-10 md:space-y-0">
            <div className="flex justify-center w-full lg:w-1/2 lg:justify-start pb-10 lg:pb-0">
              <Image
                src="/img/you-should-look-for-features-in-iot-apps-img.webp"
                alt=" IoT Development Services"
                className="rounded-md"
                width={500}
                height={500}
                loader={uploadcareLoader}
                unoptimized={true}
              />
            </div>
            <div className="w-full lg:w-1/2 text-left space-y-6 border-2 p-6 border-dashed border-[#0E1F51]">
              <div className="space-y-4">
                <h2 className="xl:text-4xl text-3xl font-bold text-[#0E1F51] ">
                  You should look for features in IoT apps!
                </h2>
              </div>
              <p className="text-base text-black">
                {`Comfygen has proven to be a trusted partner for developing mobile app development for IoT with great features and functionality. Our IoT app development solutions will help boost enhanced workflow and streamline management. We also tailor-fit the features as per the business requirements. Here are the key features that our IoT application developers focus on in order to meet their needs effectively:`}
              </p>
              <ul className="list-disc px-4 text-base">
                {JSON_DATA.myList3.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </div>
          </div>
          <div className="items-center w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12 lg:flex lg:space-x-10 md:space-y-0 lg:divide-x-2 divide-[#0E1F51]">
            <div className="w-full lg:w-1/2 text-left space-y-6">
              <div className="space-y-4">
                <h2 className="xl:text-4xl text-3xl font-bold text-[#0E1F51] ">
                  Alerts and Notifications and Data Analytics and Insights
                </h2>
              </div>
              <p className="text-base text-black">
                {`We integrate alerts and notifications to keep your users informed about critical events, threshold breaches, and system abnormalities. Our healthcare IoT app development integrates alert settings to allow users to know trigger conditions and receive notifications via email, SMS, or push notifications. We integrate advanced data analytics tools to analyze IoT data. Our IoT application development company focuses on features such as predictive analytics, trend analysis, and anomaly detection.`}
              </p>
              <ul className="list-disc px-4 text-base">
                {JSON_DATA.myList3.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </div>
            <div className="flex justify-center w-full lg:w-1/2 lg:justify-end pb-10 lg:pb-0">
              <Image
                src="/img/alerts-and-notifications-and-data-analytics-and-insights.webp"
                alt=" IoT Development Services"
                className="rounded-md"
                width={500}
                height={500}
                loader={uploadcareLoader}
                unoptimized={true}
              />
            </div>
          </div>
          <div className="items-center w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12 lg:flex lg:space-x-10 md:space-y-0">
            <div className="flex justify-center w-full lg:w-1/2 lg:justify-start pb-10 lg:pb-0">
              <Image
                src="/img/scalability-and-performance-and-integration-with-third-party-systems.webp"
                alt=" IoT Development Services"
                className="rounded-md"
                width={500}
                height={500}
                loader={uploadcareLoader}
                unoptimized={true}
              />
            </div>
            <div className="w-full lg:w-1/2 text-left space-y-6 border-2 p-6 border-dashed border-[#0E1F51]">
              <div className="space-y-4">
                <h2 className="xl:text-4xl text-3xl font-bold text-[#0E1F51] ">
                  Scalability and Performance and Integration with Third-Party
                  Systems
                </h2>
              </div>
              <p className="text-base text-black">
                {`One of our major priorities is scalability. We incorporate scalable solutions with application development in IoT that can accommodate various numbers of devices, users, and data volumes without any performance compromise. We integrate advanced features to maintain responsiveness and reliability as the IoT deployment scales. We seamlessly integrate IoT apps with third-party systems for data-driven decision-making.`}
              </p>
              <ul className="list-disc px-4 text-base">
                {JSON_DATA.myList3.map((item, index) => (
                  <li key={index}>{item}</li>
                ))}
              </ul>
            </div>
          </div>
        </section>

        <div className="w-11/12 mx-auto 2xl:w-9/12 xl:w-5/6 lg:w-11/12 py-16">
          <div className="space-y-4 text-center">
            <h2 className="text-4xl font-bold text-[#0E1F51] ">
              {" "}
              Discover Our Exclusive{" "}
              <span className="text-blue-500">
                {" "}
                Technology Stack For IoT App{" "}
              </span>{" "}
              Development{" "}
            </h2>
            <p className="text-base text-slate-800">
              At Comfygen, we use the latest technology stack for IoT app
              development. We keep up with the ongoing trends and developing
              technologies in order to create scalable, secure, and efficient
              IoT apps. Here is the essential technology stack we focus on;
            </p>
          </div>
          <div className="grid gap-16 pt-8 lg:grid-cols-3 md:grid-cols-2 xl:gap-12">
            {JSON_DATA.Solutions.map((elem) => {
              const { title, img, decs, num } = elem;
              return (
                <div
                  key={num}
                  className="p-6 space-y-4 bg-white border rounded-xl"
                >
                  <div className="flex items-center justify-center w-16 h-16 p-3 text-xl font-semibold text-white bg-orange-100 rounded-full bg-gradient-to-t">
                    <Image
                      width={100}
                      height={100}
                      src={img}
                      alt={title}
                      title="Comfygen Privited Limited"
                      className="w-16"
                    />
                  </div>
                  <h3 className="text-lg font-extrabold text-[#0E1F51] transition-all duration-200 group-hover:text-white text-left">
                    {title}
                  </h3>
                  <p className="font-medium text-left text-black break-all transition duration-200 ease-in-out  line-clamp-5 group-hover:text-white">
                    {decs}
                  </p>
                </div>
              );
            })}
          </div>
        </div>

        <section className="bg-[#F8F9FA]">
          <section className="lg:py-16 py-4 w-11/12 mx-auto space-y-10 2xl:w-9/12 xl:w-5/6">
            <div className="w-full md:text-left">
              <h2 className=" font-bold 2xl:text-4xl xl:text-3xl text-2xl text-[#0E1F51] text-center">
                {Modus?.title}
              </h2>
              <p className="text-black text-base text-center">{Modus?.decs}</p>
            </div>
            <div className="grid  gap-10 lg:grid-cols-3 md:grid-cols-2">
              {JSON_DATA.Development.map((elem: any) => {
                const { title, num, img, decs, icon } = elem;
                return (
                  <div
                    key={num}
                    className="rounded-xl bg-white  p-6 cursor-pointer transition-all duration-400 hover:translate-y-2 group"
                  >
                    <div className="flex items-center justify-center w-16 h-16 mx-auto p-4 bg-[#eaeefb] rounded-lg ">
                      <Image src={img} alt={title} width="40" height="40" />
                      {/* <span>{icon}</span> */}
                    </div>
                    <div className=" text-center space-y-1 mt-4">
                      <h3 className="text-xl  text-[#222569] text-center group-hover:text-[#2f55d4] font-semibold">
                        {" "}
                        {title}{" "}
                      </h3>
                      <p className="text-center">{decs}</p>
                    </div>
                  </div>
                );
              })}
            </div>
          </section>
        </section>
        <Portfolio />
        <div className="w-11/12 mx-auto space-y-14 2xl:w-9/12 xl:w-5/6 py-10">
          <div className="flex flex-col justify-center items-center text-center">
            <h2 className="text-3xl lg:text-4xl md:text-center text-left font-bold leading-[2rem] lg:leading-[3rem] text-[#0E1F51]">
              Comprehensive Working Methodology for Implementing IoT Development
              Solutions
            </h2>
            <p>
              Comfygen has built a strong reputation as a top leader in IoT
              application development services in India. We are known for our
              well-evaluated and high-quality workflow. Our comprehensive
              methodology in developing and deploying IoT apps will meet the
              needs of multiple clients in various industrial sectors. Here is
              the detailed methodology we follow;
            </p>
          </div>
          <div className="grid  gap-10 lg:grid-cols-3 md:grid-cols-2">
            {JSON_DATA.AppProcess.map((elem) => {
              const { title, num, decs } = elem;
              return (
                <div
                  key={num}
                  className="border p-3 space-y-2 shadow border-l-[16px] rounded-l-2xl border-[#16BDFA]"
                >
                  <p className="bg-clip-text text-transparent bg-gradient-to-t from-[#16BDFA] to-[#BE5EBC] text-xl font-bold">
                    {title}
                  </p>
                  <p className="text-base text-slate-800">{decs}</p>
                </div>
              );
            })}
          </div>
        </div>
        <TalkExpert />

        <section className=" py-10  w-11/12  space-y-4 2xl:w-9/12 xl:w-5/6 lg:w-11/12 mx-auto">
          <div className="flex flex-col justify-center text-center">
            <h2 className=" text-[#0E1F51] xl:text-4xl text-3xl font-bold xl:leading-[3rem] capitalize">
              Check Out Our Different IoT Models For Business
            </h2>
            <p>
              At Comfygen, we offer solutions for different IoT models for
              different business types for easier access. We offer highly
              flexible engagement models based on the client's needs.
            </p>
          </div>
          <div className="grid lg:grid-cols-3 grid-cols-1 ">
            {JSON_DATA.TecnologisStack.map((metaverse) => {
              return (
                <div
                  key={metaverse.num}
                  className="p-6 text-center bg-white space-y-2 hover:bg-[#000000]/60 transition-all duration-300 ease-in-out group border"
                >
                  <Image
                    src={metaverse.img}
                    alt={metaverse.title}
                    className="mx-auto"
                    width={400}
                    height={200}
                  />
                  <h3 className="bg-clip-text text-transparent bg-gradient-to-t from-[#16BDFA] to-[#BE5EBC] font-bold text-lg group-hover:text-white">
                    {metaverse.title}
                  </h3>
                  <p className="group-hover:text-white"> {metaverse.stack} </p>
                </div>
              );
            })}
          </div>
        </section>

        <section className="bg-[#F8F9FA] py-10">
          <div className="space-y-4 text-center mx-auto 2xl:w-9/12 xl:w-5/6 w-11/12 ">
            <div className="flex flex-col justify-center mx-auto">
              <h2 className="py-4 text-3xl lg:text-4xl md:text-center text-left font-bold leading-[2rem] lg:leading-[3rem] text-[#0E1F51]">
                Why Choose Comfygen for IoT App Development?
              </h2>
              <p className="text-base text-slate-900 md:text-center text-justify tracking-tight">
                We are now the top IoT app development company because of our
                innovative and flexible solutions. Businesses can make the most
                of our comprehensive IoT solutions. Choosing Comfygen for
                Xamarin IoT app development comes with several advantages:
              </p>
            </div>
            <div className="grid lg:grid-cols-2 xl:gap-10 gap-10 py-10 text-left">
              {JSON_DATA.WhyChooseComfygen.map((elem) => {
                const { title, decs, num } = elem;
                return (
                  <div
                    key={num}
                    className="space-y-4 p-6 bg-white border border-[#0E1F51] rounded-tl-2xl rounded-br-2xl"
                  >
                    <p className="text-2xl font-[800] text-[#0E1F51]">
                      {title}
                    </p>
                    <p className="text-slate-900">{decs} </p>
                  </div>
                );
              })}
            </div>
            <div className="">
              <a href="/contact-us">
                <button className="shadow-2xl hover:scale-75 transition-all duration-300 ease-in relative inline-flex items-center justify-center px-8 py-3 space-x-1 overflow-hidden text-lg font-semibold bg-gradient-to-r from-[#16BDFA] to-[#BE5EBC]  rounded cursor-pointer text-white w-fit group">
                  Let’s Get Your IoT App Development Now!
                </button>
              </a>
            </div>
          </div>
        </section>

        <section className="py-10">
          <div
            className="bg-center bg-no-repeat bg-cover lazyload lg:py-20 py-10"
            style={{ backgroundImage: `url("/img/Iot-application.webp")` }}
          >
            <div className="items-center w-11/12 mx-auto space-y-10 md:flex 2xl:w-9/12 xl:w-5/6 lg:w-11/12 md:space-x-10 md:space-y-0 bg-[#5A77B3CC] backdrop-blur-md lg:p-20 p-8 rounded-[40px]">
              <HireSection Hire={JSON_DATA.Hire} myList={JSON_DATA.myList} />
            </div>
          </div>
        </section>
        <section className="2xl:w-9/12 xl:w-5/6 lg:w-11/12 mx-auto w-11/12 py-10">
          <div className="flex flex-wrap">
            <div className="mb-12 w-full shrink-0 grow-0 basis-auto xl:mb-0 xl:w-5/12">
              <div className="flex xl:py-12">
                <Image
                  src="/img/get-additional-information-on-our-iot-app-development.webp"
                  width={781}
                  height={521}
                  blurDataURL="URL"
                  placeholder="blur"
                  loader={uploadcareLoader}
                  unoptimized={true}
                  className="w-full rounded-lg shadow-lg dark:shadow-black/20 xl:ml-[50px] z-[10]"
                  alt=" Let's Craft Your Omaha Poker Gaming Experience"
                />
              </div>
            </div>
            <div className="w-full shrink-0 grow-0 basis-auto xl:w-7/12">
              <div className="flex h-full items-center rounded-lg bg-gray-300 p-6 text-center text-black xl:pl-12 xl:text-left">
                <div className="xl:pl-12 space-y-2">
                  <h2 className="mb-6 text-3xl font-bold">
                    Get additional information on our IoT App Development
                    Services!
                  </h2>
                  <p className="">
                    Do you want additional information regarding our IoT
                    development? Get in touch with our experts in order to find
                    out the best solution to create top-notch IoT app
                    development ways. Our consultants will give you tailored
                    solutions as per your business requirements. Our
                    professional team will help you make the most of our
                    service. Your business will get comprehensive solutions with
                    software design, development, and maintenance, as well as
                    the latest technologies and trends.
                  </p>
                  <div className="pt-8">
                    <Link href="/contact-us" passHref={true}>
                      <button
                        type="button"
                        className="rounded-full border-2 border-black px-7 pb-2.5 pt-3 text-sm font-medium uppercase leading-normal text-black transition duration-150 ease-in-out hover:border-neutral-100 hover:bg-neutral-900  hover:text-neutral-100 focus:border-neutral-100 focus:text-neutral-100 focus:outline-none focus:ring-0 active:border-neutral-200 active:text-neutral-200"
                        data-te-ripple-init
                        data-te-ripple-color="light"
                      >
                        Get in touch now.
                      </button>
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </section>

        <FaqSection
          faqData={JSON_DATA.Frequently}
          title="  Iot App Development Services Company "
        />
        <BlogSection initialData={initialData} />
      </div>
    </>
  );
}

// This gets called on every request
export async function getServerSideProps({ res }) {
  const resData = await fetch(process.env.URL + "/api/v1/posts?per_page=3");
  const data = await resData.json();
  res.setHeader(
    "Cache-Control",
    "public, s-maxage=10, stale-while-revalidate=59"
  );
  return { props: { initialData: data } };
}
